{
  imports = [
    ./asus.nix
    ./audio.nix
    ./boot.nix
    ./firefox.nix
    ./flakes.nix
    ./fonts.nix
    ./hardware.nix
    ./helper.nix
    ./keyboard.nix
    ./locales.nix
    ./networking.nix
    ./nvidia.nix
    ./printing.nix
    ./unfree.nix
    ./user.nix
    ./version.nix
    ./zsh.nix
  ];
}
